# Generated by Django 6.1.1 on 2026-09-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_folder_session_folder_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
