# Generated by Django 6.1.1 on 2026-09-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_session_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
