# Generated by Django 6.1.1 on 2026-09-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_session_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='portfolio',
            field=models.BooleanField(default=False),
        ),
    ]
